//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierShopLoginApp.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    using CourierShopLoginApp.Helpers;

    public partial class CourierShopDBEntities1 : DbContext
    {
        public CourierShopDBEntities1()
            : base(GetConnectionString())
        {
            Database.CommandTimeout = 60;
            Configuration.LazyLoadingEnabled = false;
        }

        private static string GetConnectionString()
        {
            // Parse the connection string from GlobalConfig
            SqlConnectionStringBuilder sqlBuilder = new SqlConnectionStringBuilder(GlobalConfig.ConnectionString);

            EntityConnectionStringBuilder entityBuilder = new EntityConnectionStringBuilder
            {
                Provider = "System.Data.SqlClient",
                ProviderConnectionString = sqlBuilder.ToString(),
                Metadata = "res://*/DataModels.CourierShopDB.csdl|res://*/DataModels.CourierShopDB.ssdl|res://*/DataModels.CourierShopDB.msl"
            };

            return entityBuilder.ToString();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RouteLogs> RouteLogs { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
