//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierShopLoginApp.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteLogs
    {
        public int log_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string location_note { get; set; }
        public string status_note { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
